# Sets up a noetic docker environment with a noVNC server
version: '3.8'
services:
  ros_dev_env:
    container_name: ros_noetic_courses
    image: noetic_base:latest
    build: ./
    volumes: 
      - /dev/:/dev/
      - /Users/jamespuckett/.ssh:/home/rosdocker/.ssh/
      - /Users/jamespuckett/workspace/courses/CSCE635:/home/rosdocker/CSCE635/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true
  novnc:
    container_name: noetic_server
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: on-failure
networks:
  x11: 