# Sets up a humble docker environment with a noVNC server
version: '3.8'
services:
  ros_dev_env:
    container_name: ros_humble_courses
    image: humble_base:latest
    build: ./
    volumes: 
      - /dev/:/dev/
      - /Users/jamespuckett/.ssh:/home/rosdocker/.ssh/
      - /Users/jamespuckett/workspace/courses/CSCE752:/home/rosdocker/CSCE752/
      - /Users/jamespuckett/workspace/courses/MEEN689:/home/rosdocker/MEEN689/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true
  novnc:
    container_name: humble_server
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: on-failure
networks:
  x11: 